### DISCUSSION TITLE
Advice about docker socket configuration

### DISCUSSION THREAD

**Discussion by DaphneMuller** [nextcloud/app_api#304] [Q&A]
An integration partner reached out to me.

They are trying to set up the AppAPI in Nextcloud using Docker, but are encountering issues with the Docker socket configuration. They previously attempted to create a volume for the Docker socket within the Nextcloud AIO container, but it wasn't successful.

Could you advise on the recommended approach for configuring Docker access for the AppAPI in a Nextcloud AIO environment or a link to the relevant documentation? 

Are there any specific considerations we should be aware of when using volumes for the Docker socket?

**Comment by DaphneMuller** [comment]
@bigcat88

**Comment by bigcat88** [comment]
In AIO everything should work out of the box, where the DeployDemon is created automatically.

If they have some non-standard scheme, they can look at what parameters the default daemon is created with:

https://cloud-py-api.github.io/app_api/DeployConfigurations.html#nextcloud-in-docker-aio-all-in-one

After creating the Daemon, the easiest way to check it is with the "TestDeploy" button

<img width="494" alt="image" src="https://github.com/cloud-py-api/app_api/assets/13381981/4e275575-cb52-4b7d-814c-604967a89b04">

To say something more specific, we need to know at what step of TestDeploy - they have an error

**Reply by kevmax1** [reply]
Hi @bigcat88, 
Hope you're doing well,

i tried what you asked and even other cases on your link but it doesn't work i tried to enter my docker container to check if docker commands work inside but it doesn't work

<img width="429" alt="image" src="https://github.com/cloud-py-api/app_api/assets/16380947/7bcc39ed-cc2c-4527-adc5-0e75eb6f845b">

**Reply by bigcat88** [reply]
I suggest you to add a separate container with DockerSocketProxy to your docker-compose file and map `docker.sock` into it, and in AppAPI create daemon to point to the DockerSocketProxy container

**Reply by kevmax1** [reply]
Is there an example repository I can look at?

**Reply by bigcat88** [reply]
with what values to init docker-socket-proxy container you can found information it it repository

there is currently no example for docker-compose file, feel free to make a PR to the DockerSocketProxy repo with that info

**Reply by kevmax1** [reply]
Hello @bigcat88,
I was able to configure the docker-socket-proxy in my docker-compose and add a daemon and it already communicates well with nextcloud but I get a 403 error when I try to test the daemon or install an external application apparently the image registry on google is protected. 
Can you help me with this?

**Reply by andrey18106** [reply]
Hi, @kevmax1!

Could you please check for any logs of the docker-socket-proxy which are rejected with 403?

The HTTP 403 error means, that something from the following is wrong and can't be verified by haproxy:

1. SSL cert (if you use https)
2. haproxy password
3. The route to Docker API is not allowed for some reason (which shouldn't be the case, we don't use routes, that are not allowed in our docker-socket-proxy haproxy cfg).


- For the first case, if you've configured daemon with https, could you confirm if you have added your `cert.pem` in nextcloud (https://github.com/cloud-py-api/docker-socket-proxy?tab=readme-ov-file#docker-with-tls): `sudo -u www-data php occ security:certificates:import /path/inside/nextcloud/container/to/cert.pem`.
- Does the "Check connection" button work and ping command successfully sent to the Docker API?

If this doesn't help, would you mind to share the docker-compose file you've created for docker-socket-proxy?

> apparently the image registry on google is protected

What ExApp are you trying to install?
If the docker daemon connection is fine, and only issue with accessing container registry:

Currently, we don't use and don't support the docker container registry auth credentials, the Docker images must be available publicly. But if this is the private ExApp image which images are accessible only with auth, we might consider adding this possibility, I'll file an issue for that if this is the case.
Is there any reasons of using only Google container registry?

**Reply by kevmax1** [reply]
Hi @andrey18106,
**This is the error i obtain when i try to activate an apps from the store (ex: AllImageGeneratorBot, Local large language model, ...):** 
{"reqId":"qziHZtt6mUYNDVD5C7YL","level":3,"time":"2024-07-09T09:52:46+00:00","remoteAddr":"","user":"--","app":"app_api","method":"","url":"--","message":"ExApp llm2 deployment failed. Error: Failed to pull image, GuzzleException occur: Client error: `POST http://nextcloud-appapi-dsp:2375/v1.41/images/create?fromImage=ghcr.io%2Fnextcloud%2Fllm2%3A1.2.5` resulted in a `403 Forbidden` response","userAgent":"--","version":"29.0.1.1","data":{"app":"app_api"}}
**The "Check connection" button work well**
*This is the content of my docker-compose:*
```
version: '3'

volumes:
  nextcloud29:
  db4:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db4:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true

  app:
    image: nextcloud:29.0.1
    #platform: linux/arm64/v8
    restart: always
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - nextcloud29:/var/www/html
      - ./apps29:/var/www/html/apps
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  nextcloud-appapi-dsp:
    image: tecnativa/docker-socket-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
