### ISSUE TITLE
ExApp is requested through its port (remote host deployment)

### ISSUE THREAD

**Issue by ThibautPlg** [nextcloud/app_api#526]
### Describe the bug

Hi,
My issue is very close to https://github.com/nextcloud/app_api/issues/522 but with a different deployment method so I'm making my own issue. 

I'm using the "remote host deployment" method with my whole docker stack being on host B and my nextcloud on host A. I have an nginx reverse-proxy on host B that does a proxypass to the container. (So I'm only exposing 80/443)

I've correctly registered the Deploy Daemons, with success on the "check connection" step. 
However, when deploying a Test deploy exapp through the AppApi interface, everything goes according to plan until the heartbeat. 

From my understanding, the use of the Docker Socket Proxy should help me to **not** expose a port per container. However, by looking at my Nextcloud Logs, I can see that the heartbeat is trying to contact the B host through the newly deployed 23000 port. (Which doesn't work, because it's not exposed)

```
{"reqId":"1ZUQd10crMEu3t4OLI8X","level":2,"time":"2025-03-05T17:13:10+01:00","remoteAddr":"","user":false,"app":"app_api","method":"","url":"--","message":"Failed heartbeat on https://host-b.example:23000 for 10 times. Most recent status=0, error: cURL error 7: Failed to connect to host-b.example port 23000: No route to host (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://host-b.example:23000/heartbeat","userAgent":"--","version":"31.0.0.18","data":{"app":"app_api"}}
```
Am I missing something? Shouldn't Nextcloud contact the extapp though the proxy? 

This is my compose file:
```
version: '3.7'
 
services:
  nextcloud-docker-socket-proxy:
    privileged: true
    restart: unless-stopped
    container_name:  nextcloud-appapi-dsp
    image: ghcr.io/cloud-py-api/nextcloud-appapi-dsp:release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
       NC_HAPROXY_PASSWORD: "mypassword"
    ports:
      - 127.0.0.1:2375:2375
```
And the nginx reverse proxy block:
```
location / {
      proxy_pass http://localhost:2375;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_buffering off;
      proxy_request_buffering off;
      proxy_http_version 1.1;
      proxy_intercept_errors on;
    }
```

Best regards,

### Steps/Code to Reproduce

Test deploy using a remote docker host

### Expected Results

Nextcloud should try to contact the container through the proxy, being the only exposed container/port

### Actual Results

Nextcloud contacts through the newly created container port

### Setup configuration

Nextcloud 31.0.0
app_api 5.0.2
