### ISSUE TITLE
webhook register in conbination of AppAPI will not fill out userId

### ISSUE THREAD

**Issue by PatrickPromitzer** [nextcloud/app_api#576]
### Describe the bug

Short version: https://github.com/cloud-py-api/nc_py_api/issues/355#issuecomment-2858237940

Location: ExApp docker image -> from tthe [to_gif](https://github.com/cloud-py-api/nc_py_api/tree/main/examples/as_app/to_gif) example

Registering a webhook in an  AppAPI with this code
```python
nc.webhooks.register(
                    http_method="POST",
                    uri="/basic_file_checker",
                    event="OCP\\Files\\Events\\Node\\BeforeNodeWrittenEvent",
                )
```
works, but after getting a call in the this function

```python
def file_event_handler(event_data: dict, nc: NextcloudApp):
    try:
        nc_file = nc.files.by_id(str(event_data["event"]["node"]["id"]))
        print(nc_file)
    except Exception as e:
        error_string = 'Exception:\n', traceback.format_exc() + "\n" + str(e)
        nc.log(LogLvl.ERROR, f"Error: {error_string}")
        raise e


@APP.post("/basic_file_checker")
async def basic_file_checker(
        event_data: dict,
        nc: Annotated[NextcloudApp, Depends(nc_app)],
        background_tasks: BackgroundTasks,
):
    background_tasks.add_task(file_event_handler, event_data, nc)
```
an Exception raises
```
Traceback (most recent call last):
  File "/app/lib/main.py", line 53, in file_event_handler
    nc_file = nc.files.by_id(str(event_data["event"]["node"]["id"]))
  File "/usr/local/lib/python3.13/site-packages/nc_py_api/files/files.py", line 65, in by_id
    result = self.find(req=["eq", "fileid", file_id])
  File "/usr/local/lib/python3.13/site-packages/nc_py_api/files/files.py", line 86, in find
    return lf_parse_webdav_response(self._session.cfg.dav_url_suffix, webdav_response, request_info)
  File "/usr/local/lib/python3.13/site-packages/nc_py_api/files/_files.py", line 345, in lf_parse_webdav_response
    return _parse_records(dav_url_suffix, _webdav_response_to_records(webdav_res, info), response_type)
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/nc_py_api/files/_files.py", line 349, in _webdav_response_to_records
    check_error(webdav_res, info=info)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/nc_py_api/_exceptions.py", line 65, in check_error
    raise NextcloudException(status_code, reason=codes(status_code).phrase, info=info)
nc_py_api._exceptions.NextcloudException: [401] Unauthorized <find: , [], >
[401] Unauthorized <find: , [], >
```
bigcat88 looked into the problem and came to the conclusion, that the userID for permissions will not get filled out by default.
Adding the usedID after the call will give the request the right permission
```python

def file_event_handler(event_data: dict, nc: NextcloudApp):
    nc.set_user(event_data["user"]["uid"])  # **Add this line**
    try:
        nc_file = nc.files.by_id(str(event_data["event"]["node"]["id"]))
        print(nc_file)
    except Exception as e:
        error_string = 'Exception:\n', traceback.format_exc() + "\n" + str(e)
        nc.log(LogLvl.ERROR, f"Error: {error_string}")
        raise e
```

Explanation:
https://github.com/cloud-py-api/nc_py_api/issues/355#issuecomment-2858237940

### Steps/Code to Reproduce

1.) prepare and start a REST API server for debuging
https://github.com/ynsrc/python-simple-rest-api

I added an function to save the logs into files.
Download the server.py file, change the port to 2998 and add this functions
```python
import pathlib

@api.post("/log_string")
def log_string(args):
    args = {key.lower(): value for key, value in args.items()}
    print("------------------------")
    print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
    write_error_to_file(args)
    print(args)
    save_note_events(args)
    write_bytes_to_file(args)
    return "OK"


def write_error_to_file(args):
    if "error" not in args:
        return
    print("Error: ", args["error"])
    error_string = args["error"]
    temp_folder_parth = pathlib.Path("..", "temp", "error")
    if not temp_folder_parth.exists():
        temp_folder_parth.mkdir(parents=True, exist_ok = True)

    file_name = "error" + "_-_" + str(time.strftime("%Y-%m-%d_%H-%M-%S", time.localtime())) + ".txt"
    output_file_path = temp_folder_parth.joinpath(file_name)

    if isinstance(error_string, list):
        error_string = " ".join(error_string)

    with open(output_file_path, "w") as f:
        f.write(error_string)

def write_bytes_to_file(log_json):
    if "bytes" not in log_json:
        return
    data_bytes = log_json["bytes"]
    name = "temp.raw"
    if "name" in log_json:
        name = log_json["name"]

    temp_folder_parth = pathlib.Path("temp")
    if "id" in log_json:
        temp_folder_parth = temp_folder_parth.joinpath(log_json["id"])

    output_file = temp_folder_parth.joinpath(name)
    bytes_data = bytes.fromhex(data_bytes)
    with open(output_file, "wb") as f:
        f.write(bytes_data)

    print("Bytes written to file: ", output_file)

def save_note_events(log_json):
    if "data" not in log_json:
        return
    log_data = log_json["data"]
    temp_folder_parth = pathlib.Path("temp")
    if "id" in log_json:
        temp_folder_parth = temp_folder_parth.joinpath(log_json["id"])
    if not temp_folder_parth.exists():
        temp_folder_parth.mkdir(parents=True, exist_ok = True)

    file_name = str(time.strftime("%Y-%m-%d_%H-%M-%S", time.localtime()))  + "_-_" + str(time.time_ns()) + "-" + str(random.Random().randint(0, 9999))
    if "event_subtype" in log_data:
        file_name = log_data["event_subtype"] + "_-_" + file_name
    output_file_path = temp_folder_parth.joinpath(file_name + ".json")
    i = 0
    while output_file_path.exists():
        output_file_path = temp_folder_parth.joinpath(file_name + "_" + str(i).zfill(4) + ".json")
    with open(output_file_path, "w") as f:
        f.write(json.dumps(log_data, indent=4))
```
2.) download the [to_gif](https://github.com/cloud-py-api/nc_py_api/tree/main/examples/as_app/to_gif) example

3.) add "requests" to the requirements.txt

4.) replace the "main.py" with this code
```python
import pathlib
import time
import traceback
import requests

from contextlib import asynccontextmanager
from fastapi import FastAPI, BackgroundTasks

from nc_py_api import NextcloudApp
from nc_py_api.ex_app import AppAPIAuthMiddleware, LogLvl, run_app, set_handlers, nc_app
from fastapi import Depends
from typing import Annotated

LOG_LOCAL_HOST_STRING = "127.0.0.1"


def file_event_handler(event_data: dict, nc: NextcloudApp):
    try:
        #nc.set_user(event_data["user"]["uid"])
        nc_file = nc.files.by_id(str(event_data["event"]["node"]["id"]))

    except Exception as e:
        error_string = 'Exception:\n', traceback.format_exc() + "\n" + str(e)
        response = requests.post(f"http://{LOG_LOCAL_HOST_STRING}:2998/log_string", json={"error": str(error_string)})
        nc.log(LogLvl.ERROR, f"Error: {error_string}")
        raise e


@asynccontextmanager
async def lifespan(app: FastAPI):
    set_handlers(app, enabled_handler)
    yield


APP = FastAPI(lifespan=lifespan)
APP.add_middleware(AppAPIAuthMiddleware)


@APP.post("/basic_file_checker")
async def basic_file_checker(
        event_data: dict,
        # files: ActionFileInfoEx,
        nc: Annotated[NextcloudApp, Depends(nc_app)],
        background_tasks: BackgroundTasks,
):
    response = requests.post(f"http://{LOG_LOCAL_HOST_STRING}:2998/log_string",
                             json={"ID": "basic_file_checker", "called": "true", "data": event_data})
    background_tasks.add_task(file_event_handler, event_data, nc)


def enabled_handler(enabled: bool, nc: NextcloudApp) -> str:
    print(f"enabled={enabled}")

    response = requests.post(f"http://{LOG_LOCAL_HOST_STRING}:2998/log_string",
                             json={"ID": "enabled_handler", "enabled": enabled})
    try:
        if enabled:
            nc.webhooks.register(
                http_method="POST",
                uri="/basic_file_checker",
                event= "OCP\\Files\\Events\\Node\\NodeWrittenEvent",
            )
            wh_list = nc.webhooks.get_list()
            wh_list = [i.__dict__ for i in wh_list]
            response = requests.post(f"http://{LOG_LOCAL_HOST_STRING}:2998/log_string",
                                     json={"id": "webhook list", "data": wh_list})
        nc.log(LogLvl.INFO, f"App enabled: {enabled}")
    except Exception as e:
        error_string = 'Exception:\n', traceback.format_exc() + "\n" + str(e)
        response = requests.post(f"http://{LOG_LOCAL_HOST_STRING}:2998/log_string", json={"error": error_string})
        nc.log(LogLvl.ERROR, f"Error: {error_string}")

    return ""


if __name__ == "__main__":
    pathlib.Path("temp").mkdir(parents=True, exist_ok=True)
    run_app(
        "main:APP",
        log_level="trace",
    )

```

### Expected Results

using the ```nc: NextcloudApp``` variable without the need to set a user in the ExApp application.

### Actual Results

Manually (with code) set the user for the api call. 

### Setup configuration

I install the app with an bash file I wrote.
```
#!/bin/bash
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${script_dir}" || exit

APP_ID="basic_file_checker"
APP_SOURCE="127.0.0.1:5000"
NEXTCLOUD_DOCKER_CONTAINER_NAME="nextcloud-server"
DOCKER_CONFIG_NAME="docker_local"

APP_NAME="Basic_File_checker"
APP_VERSION="1.0.0"
APP_SECRET="12345"
APP_PORT="2981"

JSON_INFO="{\"id\":\"${APP_ID}\",\"name\":\"${APP_NAME}\",\"source\":\"${APP_SOURCE}\",\"daemon_config_name\":\"${DOCKER_CONFIG_NAME}\",\"version\":\"${APP_VERSION}\",\"secret\":\"${APP_SECRET}\",\"port\":${APP_PORT},\"routes\":[{\"url\":\".*\",\"verb\":\"GET,POST,PUT,DELETE\",\"access_level\":1,\"headers_to_exclude\":[]}]}"
docker build -t 127.0.0.1:5000/${APP_ID} .
docker push 127.0.0.1:5000/${APP_ID}

echo docker exec ${NEXTCLOUD_DOCKER_CONTAINER_NAME} php occ app_api:app:unregister ${APP_ID} --silent --force || true
docker exec ${NEXTCLOUD_DOCKER_CONTAINER_NAME} php occ app_api:app:unregister ${APP_ID} --silent --force || true
echo docker exec ${NEXTCLOUD_DOCKER_CONTAINER_NAME} php occ app_api:app:register ${APP_ID} --force-scopes --json-info ${JSON_INFO} # docker_scope_all
docker exec ${NEXTCLOUD_DOCKER_CONTAINER_NAME} php occ app_api:app:register ${APP_ID} --force-scopes --json-info ${JSON_INFO} # docker_scope_all
```
The nextcloud server is in an docker, too.

```
version: '3.2'

services:
  db:
    image: postgres
    restart: always
    network_mode: host
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    container_name: nextcloud-db

  app:
    image: nextcloud
    restart: always
    privileged: true
    network_mode: host
    #ports:
    #  - 2980:2980
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_config:/etc/apache2/
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db
    container_name: nextcloud-server

  cron:
    image: nextcloud
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    container_name: nextcloud-cron
    extra_hosts:
    - "host.docker.internal:host-gateway"


  nextcloud_appapi_ds:
    image: ghcr.io/nextcloud/nextcloud-appapi-dsp:release
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NC_HAPROXY_PASSWORD=some_secure_password
    container_name: nextcloud-appapi-dsp
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/patrickpromitzer/PycharmProjects/dm-nextcloud/data/db/
  nextcloud:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/patrickpromitzer/PycharmProjects/dm-nextcloud/data/nextcloud/
  nextcloud_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/patrickpromitzer/PycharmProjects/dm-nextcloud/data/nextcloud_config/
```
Version
Nextcloud Hub 10 (31.0.2)
Nextcloud Hub 10 (31.0.4)
